-- Radar Electoral / Meta Evidencias v1
-- Base para revisión colaborativa y publicación controlada.

create extension if not exists pgcrypto;

create type public.app_role as enum ('ADMIN', 'ANALISTA', 'PUBLICO');
create type public.review_status as enum ('PENDIENTE', 'EN_REVISION', 'VALIDADO', 'OBSERVADO', 'PUBLICADO');
create type public.content_classification as enum (
  'PROPAGANDA_ELECTORAL_DIRECTA',
  'PROPAGANDA_ELECTORAL_INDIRECTA',
  'PUBLICIDAD_POLITICA_NO_ELECTORAL',
  'INSTITUCIONAL_PARTIDARIA',
  'PERSONAL',
  'INFORMATIVO',
  'NO_CORRESPONDE',
  'REQUIERE_REVISION'
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role public.app_role not null default 'ANALISTA',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.runs (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  process text not null default 'PRIMERA ENTREGA',
  bot_version text,
  source_file text,
  total_ads integer not null default 0,
  uploaded_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.parties (
  id uuid primary key default gen_random_uuid(),
  canonical_name text unique not null,
  short_name text,
  active boolean not null default true
);

create table if not exists public.assignments (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.runs(id) on delete cascade,
  party_id uuid not null references public.parties(id) on delete cascade,
  analyst_id uuid not null references public.profiles(id),
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  unique(run_id, party_id)
);

create table if not exists public.ads (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.runs(id) on delete cascade,
  party_id uuid references public.parties(id),
  library_id text not null,
  candidate text,
  page_name text,
  office text,
  payer text,
  ad_status text,
  platforms text,
  date_start date,
  date_end date,
  spend_text text,
  spend_min numeric,
  spend_max numeric,
  impressions_text text,
  impressions_min bigint,
  impressions_max bigint,
  description text,
  source_url text,
  raw_json jsonb not null default '{}'::jsonb,
  review_status public.review_status not null default 'PENDIENTE',
  classification public.content_classification,
  message_type text,
  reviewer_note text,
  reviewer_id uuid references public.profiles(id),
  reviewed_at timestamptz,
  admin_note text,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  unique(run_id, library_id)
);

create table if not exists public.evidence_files (
  id uuid primary key default gen_random_uuid(),
  ad_id uuid not null references public.ads(id) on delete cascade,
  evidence_type text not null,
  file_path text not null,
  sha256 text,
  sort_order integer not null default 0,
  mime_type text,
  public_visible boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id),
  entity_type text not null,
  entity_id text not null,
  action text not null,
  previous_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

insert into public.parties (canonical_name, short_name)
values
 ('ALIANZA PARA EL PROGRESO','APP'),
 ('PARTIDO DEMOCRÁTICO SOMOS PERÚ','SOMOS PERÚ'),
 ('PODEMOS PERÚ','PODEMOS'),
 ('PARTIDO RENOVACIÓN POPULAR','RENOVACIÓN POPULAR')
on conflict (canonical_name) do nothing;

alter table public.profiles enable row level security;
alter table public.runs enable row level security;
alter table public.parties enable row level security;
alter table public.assignments enable row level security;
alter table public.ads enable row level security;
alter table public.evidence_files enable row level security;
alter table public.audit_log enable row level security;

-- Primera política básica: los datos marcados PUBLICADOS serán visibles sin login.
drop policy if exists "public can read published ads" on public.ads;
create policy "public can read published ads" on public.ads
for select using (published = true);

drop policy if exists "public can read active parties" on public.parties;
create policy "public can read active parties" on public.parties
for select using (active = true);

-- Las políticas privadas se endurecerán al conectar Auth, asignaciones y storage.
